name: golden_presenter
description: A pure dart html golden page generator.
version: 0.0.2
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  path: ^1.9.0
  equatable: ^2.0.5
  args: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  lints: ^2.1.1
  test: ^1.25.4
