name: golden_presenter
description: A pure dart html golden page generator.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3
  path: ^1.8.2
  equatable: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lints: ^2.0.0
  test: ^1.16.0
